language: python

# Python versions to test
python:
    - "2.6"
    - "2.7"

# Install dependencies
install: 
 - "pip install -r requirements.txt"
 - "sudo apt-get install at" 

# Run tests
script: "bin/cylc test-battery -- --verbose --failures"

# Print results
after_script: 
 - "find /tmp/cylc-tests -type f"
 - "cat /tmp/cylc-tests/*/*"
