# Configuration for the Travis continuous integration system
# ==========================================================
# 
# Travis is a free service for running automatic tests on Github repositories.
# This file configures Travis for Cylc, telling it how to install Cylc and run
# the test battery.
# 
# Test results get posted back to Github. By default Travis will run tests on any
# pull requests, adding a comment on the pull request page to say if the tests
# pass or fail, it will also test any new commits, showing the test results on
# the branch page, e.g. https://github.com/cylc/cylc/branches.
# 
# Connecting a Cylc branch
# ------------------------
# 
# To make use of Travis you will first need to create a fork of Cylc in Github.
# Log in to https://travis-ci.org using your Github credentials, it will ask for
# permission to see your repositories, set the status of branches (whether the
# build passes or fails tests) and create hooks so Travis gets notified of new
# commits.
# 
# Travis will create a list of all of your public Github repositories, you can
# enable automatic tests for a repository using the switches in this list.
# 
# More information for Travis can be found at http://docs.travis-ci.com/user/getting-started/

---
language: python

before_install:
    # Setup SSH
    - ssh-keygen -t rsa -f ~/.ssh/id_rsa -N "" -q
    - cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
    - ssh-keyscan -t rsa localhost >> ~/.ssh/known_hosts

    # Setup virtualenv (using system packages for pygtk)
    - virtualenv --system-site-packages $HOME/virtualenv/cylc 
    - echo "source $HOME/virtualenv/cylc/bin/activate" >> ~/.profile

    # Make sure Cylc is in PATH when running jobs
    - echo "export PATH=$PWD/bin:\$PATH" >> ~/.profile

    - cat ~/.profile
    - source ~/.profile


# These commands are run before the test
install: 
    # Install dependencies
    - sudo apt-get install build-essential
    - sudo apt-get install at python-pip python-dev libgraphviz-dev python-gtk2-dev
    - pip install -r requirements.txt

# Run tests
script: 
    - which python
    - ssh localhost cylc help
    - cylc test-battery tests/triggering/01-or-conditional.t -- -j 4

# Check output
after_script:
    - for file in $(find $HOME/cylc-run -type f); do echo; echo "== $file =="; cat $file; done
    #- for file in $HOME/cylc-run/*/log/suite/{out,err}; do echo; echo "== $file =="; cat $file; done
    #- for file in /tmp/cylc-tests-travis/triggering/*/*; do echo; echo "== $file =="; cat $file; done
